### ISSUE TITLE
 Come up with an app/project idea

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/large-group-project-placeholder#1]
We can use this as a thread to discuss potential project ideas. I would like to build something that is actually used/useful beyond the scope of something to turn in and get a good grade. If we all buy in to the idea we might be able to make something really cool!

**Comment by mplekunov** [comment]
You know Tinder? Basically, an app for hook ups... Let's build Binder it will be an app for finding good teammates for group projects.

**Comment by mplekunov** [comment]
Joking aside, we can build a social media app, like working one (facebook copycat?)

**Comment by mplekunov** [comment]
We can also build a file storage (cloud storage, like onedrive/google drive/Mega), though, once again, not gonna be useful :(

**Comment by mplekunov** [comment]
I already told you about Hurrican Tracker before, but we will need to find a data source for that one... Like we will need to use some open source provider which will give us info about storms/hurricanes around the world.

**Comment by mplekunov** [comment]
We could also build a better UCF APP 🤣

**Comment by BryanVeith** [comment]
> We could also build a better UCF APP 🤣

a better version of myucf too 🤣

**Comment by mplekunov** [comment]
The last idea, we could build an app which would make it easier to find some goods which you want to buy online. For example, let's say you are looking for Intel core i7 CPU, this app would have a search bar and basically when you look for an item it will find all items which satisfy the search query. Then, when you click on the item it will show its price on NewEgg, BestBuy, Amazon, Ebay etc.

**Comment by mplekunov** [comment]
For this we could either use API of different marketplaces or parse their webpage (when API is not available)

**Comment by mplekunov** [comment]
This is the only one that comes to mind which you could use outside of the school project... Like sometimes searching for things is very tedious because you need to search for the same thing on different site, but here it's basically one place to look over several sites at the same time. Sounds pretty useful to me.

**Comment by mplekunov** [comment]
We could also make it possible for user to log in on different platforms through our app

**Comment by mplekunov** [comment]
Like they could log in in amazon/bestbuy/ebay/newegg etc and then use our app to order items on different platforms at the same time, basically without leaving our app.

**Comment by BryanVeith** [comment]
The only idea I have rn is something that asks you to sign up and when you do it asks for your hobbies (sports/art/etc) and your skill level in them. Then it can put you in a group message with people in similar hobbies (it could either be a when-and-where-to-meet (app would need to determine locations that fit criteria) for hobbies or a chat discussion board or both).

**Comment by mplekunov** [comment]
> The only idea I have rn is something that asks you to sign up and when you do it asks for your hobbies (sports/art/etc) and your skill level in them. Then it can put you in a group message with people in similar hobbies (it could either be a when-and-where-to-meet (app would need to determine locations that fit criteria) for hobbies or a chat discussion board or both).

So is it gonna be like a social media app but focused on finding people with the same hobbies/interests?

**Comment by BryanVeith** [comment]
> > The only idea I have rn is something that asks you to sign up and when you do it asks for your hobbies (sports/art/etc) and your skill level in them. Then it can put you in a group message with people in similar hobbies (it could either be a when-and-where-to-meet (app would need to determine locations that fit criteria) for hobbies or a chat discussion board or both).
> 
> So is it gonna be like a social media app but focused on finding people with the same hobbies/interests?

yeah

**Comment by nashirj** [comment]
Other things we should (optionally) consider when picking a project idea (this is definitely out of scope for the project, but would look good if we are able to design with answers to this in mind and talk about it in our presentation):
- What is the “problem” the product is trying to solve? Is it clear when the problem is solved? What happens if the problem is not solved?
- Who are your target users? Are they aware of the problem? Are they actively trying to find a solution? If so, how many of them?
- What are the competitive solutions for solving this problem? What do they do well or not well?
- How will the product (web or mobile app) improve over the current solutions / or solve a new problem?
- How do users browse the web or use their devices?
- If the product encompasses eCommerce, does it integrate with other channels (omnichannel or single channel)?

**Comment by nashirj** [comment]
> The last idea, we could build an app which would make it easier to find some goods which you want to buy online. For example, let's say you are looking for Intel core i7 CPU, this app would have a search bar and basically when you look for an item it will find all items which satisfy the search query. Then, when you click on the item it will show its price on NewEgg, BestBuy, Amazon, Ebay etc. as well as the link to the item page on the respective site (we could make it nice like there is an amazon button/bestbuy button and stuff)

https://pcpartpicker.com/ does something similar to this; would your idea be for any type of item?

**Comment by mplekunov** [comment]
> > The last idea, we could build an app which would make it easier to find some goods which you want to buy online. For example, let's say you are looking for Intel core i7 CPU, this app would have a search bar and basically when you look for an item it will find all items which satisfy the search query. Then, when you click on the item it will show its price on NewEgg, BestBuy, Amazon, Ebay etc. as well as the link to the item page on the respective site (we could make it nice like there is an amazon button/bestbuy button and stuff)
> 
> https://pcpartpicker.com/ does something similar to this; would your idea be for any type of item?

Yeah, I was thinking for any item, not only parts.

**Comment by mplekunov** [comment]
And yeah, I was partially influenced by parts picker 🤣

**Comment by nashirj** [comment]
> I already told you about Hurricane Tracker before, but we will need to find a data source for that one... Like we will need to use some open source provider which will give us info about storms/hurricanes around the world.

I like this idea, but I feel like there are already a lot of things that do this :thinking: what would our app do that isn't already available

**Comment by mplekunov** [comment]
Not sure if there an app that would allow you to order items from other sites without visiting them though :thinking:

**Comment by mplekunov** [comment]
But it's not like our only idea anyway, so I was just trying to come up with something 🤣

**Comment by nashirj** [comment]
> > > The only idea I have rn is something that asks you to sign up and when you do it asks for your hobbies (sports/art/etc) and your skill level in them. Then it can put you in a group message with people in similar hobbies (it could either be a when-and-where-to-meet (app would need to determine locations that fit criteria) for hobbies or a chat discussion board or both).
> > 
> > 
> > So is it gonna be like a social media app but focused on finding people with the same hobbies/interests?
> 
> yeah

I like this idea too, I think there are a lot of apps that try to do something like this, but they're targeted at like 1:1 friendships. A lot of dating apps have something for this now, where you can search for friends instead of dates. And then there is meetup which lets you join groups based on shared interests. Could be cool to combine; I feel like it would be really useful on college campuses; I know it can be hard to meet people with shared interests

**Comment by nashirj** [comment]
> But it's not like our only idea anyway, so I was just trying to come up with something rofl

It's a good idea, I like it :)

**Comment by nashirj** [comment]
> > We could also build a better UCF APP rofl
> 
> a better version of myucf too rofl

This is the one :laughing:

**Comment by mplekunov** [comment]
> > > We could also build a better UCF APP rofl
> > 
> > 
> > a better version of myucf too rofl
> 
> This is the one 😆

hard to pull off because their design (UI) is not that bad and we only have like what... 3 weeks

**Comment by mplekunov** [comment]
So like unless you are gonna go REALLY hard on the design, then I'm down, otherwise we won't be able to pull it off (UI wise)

**Comment by nashirj** [comment]
# app ideas

## food related
- tell me what is in my fridge and when it expires; requires user inventorying their purchases when they buy food; optionally could take a picture of groceries and it would auto populate items? would be hard to get expiration dates this way though
- enter in the basic items I have in my refrigerator and get recipes with the ingredients that I have; or I can type in a certain dish (spaghetti, for example), and it'll tell me if I have what I need. If not, it'll tell me the ingredients I'm missing then add them to a shopping list that is also built into the app: supercook.com
- github of food recipes: can fork recipes, modify them, propose modifications to people's recipes, create issues with people's recipes; key would be making a nice post page for each recipe containing all details and images and stuff; would be nice to show step by step how to make recipe with pictures/videos at each step


## social
- a study group app for students; chat rooms for course topics where you can study together on certain topics of the class over either live video chat or text chat; need to think of why people would use this and not just use discord. maybe each channel could have community curated resources associated with them
- synchronized activity (music/tv/etc) app; listen along in the same place
- a dating app, but specifically for dog owners, can get matched by your dogs' personalities
- tinder but for bands/musicians; could also have a feed that coordinates jam sessions/meetups; problem is that you might burn through connections too fast if you don't have many musicians sign up for the app
- tinder but for project collaborators - https://www.reddit.com/r/AppIdeas/comments/eo0hms/tinder_but_for_finding_sideproject_collaborators/, https://www.reddit.com/user/heycollab/comments/esrbf3/introducing_heycollabio_making_finding_side/?utm_source=share&utm_medium=web2x, https://heycollab.io/
- an app that matches videogame players with people with disabilities (or who just want to tell someone how to play) allowing them to "backseat" and enjoy the experience - https://www.reddit.com/r/AppIdeas/comments/hfp6bg/an_app_that_matches_videogame_players_with_people/


## quality of life
- better version of when2meet, mobile friendly, add new features
- sightseeing tour generator; use google maps API and plan best route between sightseeing destinations
- an app that tells a good midway coffee shop, restaurant, bar, etc. between two addresses
- something to make the process of applying for jobs easier; maybe a chrome extension that autofills job app fields or something; or an app that tracks the status of all your applications, what stage you are in the process, what companies you applied to, where you're applying next etc
- A place where people reading the same book can talk about it on a per chapter basis with no spoiler alerts - https://www.reddit.com/r/AppIdeas/comments/iwdyk9/a_place_where_people_reading_the_same_book_can/
- app that lets you pick where to eat/what to watch; like tinder but you and a friend swipe on available options; you both can see your matches. could over time learn preferences based on what you've "liked" https://noyoupick.one/lobster, https://play.google.com/store/apps/details?id=com.tasteio
- food/activity chooser for group of friends/family/housemates: can send polls to a selected group of my contacts e.g. send a poll to (say) my five buddies with the question "what are we up tonight?" with some preselected answers by me and one "neither of them" option. they receive a push notification with a pop up of the question and the answers. Like "club", "bar" and "nothing"


## assistive technology
- an assistant that could wait for you when you've been put on hold by customer service, tell the person to wait when they finally pick up, and ring an alarm to get your attention (I have no clue how we would do this)
- something like plantsnap or picturethis: automatic identification of object using camera; could do it for dogs, cars, etc
- low latency realtime music collaboration app (this seems really hard)
- app that transcribes speech from multiple people and identifies each speaker and what they said; used for people that are hard of hearing; sort of like what zoom/youtube do with automatic transcription, but you can have this running and feed in system audio, or audio from a microphone


## productivity
- cultivate, an app where you water plants that represent the things you value in life; take ideas from forest and plant nanny - https://www.reddit.com/r/AppIdeas/comments/lge324/app_idea_cultivate_an_app_where_you_water_plants/, https://play.google.com/store/apps/details?id=de.pineappleapps.cultivate


## misc
- app that shows what two people combined will look like; could use GANs, http://babyfacegenerator.com/, https://apps.apple.com/us/app/future-baby-generator/id1219189531, https://www.reddit.com/r/AppIdeas/comments/j4g82k/blender_dating_app/

**Comment by mplekunov** [comment]
> something to make the process of applying for jobs easier; maybe a chrome extension that autofills job app fields or something; or an app that tracks the status of all your applications, what stage you are in the process, what companies you applied to, where you're applying next etc

if we could combine both of these:
> tell me what is in my fridge and when it expires; requires user inventorying their purchases when they buy food; optionally could take a picture of groceries and it would auto populate items? would be hard to get expiration dates this way though
> enter in the basic items I have in my refrigerator and get recipes with the ingredients that I have; or I can type in a certain dish (spaghetti, for example), and it'll tell me if I have what I need. If not, it'll tell me the ingredients I'm missing then add them to a shopping list that is also built into the app: supercook.com

It would be a very helpful app to me personally because I cook myself lol

**Comment by nashirj** [comment]
The only problem with those two ideas is that there are already existing solutions: [food](https://www.escoffieronline.com/top-apps-for-finding-recipes-for-ingredients-you-already-have/), [job app tracking](https://huntr.co/). If we did these it would be nice to think of we could set it apart

**Comment by mplekunov** [comment]
I mean... there will always be an existing solution somewhere... When someone opens a bank, there are other banks already existing, so they make their bank better and make sure it stands out among competitors.

**Comment by nashirj** [comment]
That's true :)

**Comment by nashirj** [comment]
If we go with the food app, we might be able to use the [Clarifai API](https://help.clarifai.com/hc/en-us/articles/360061663733-Identify-food-items-in-your-images) to identify food items in images; we could take a picture of groceries and use that to update the inventory of items in the fridge or something like that

**Comment by nashirj** [comment]
Over discord, we all agreed that we'd make a food related app using some of the ideas suggested above
