### ISSUE TITLE
Decide on tech stack

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/large-group-project-placeholder#2]
We need a tech stack that has a web and mobile component. We can use the same shared backend for both the mobile and web apps.

## Web front-end framework options:
- Vue (primarily open source, apparently most beginner-friendly)
- React (made by FB, very commonly used, steeper learning curve than Vue)
- Angular (made by Google, uses TypeScript and MVC, steepest learning curve)

We can optionally use TypeScript instead of vanilla JS, which will help catch some classes of errors before runtime; I believe we have to use TypeScript if we decide to use Angular. Also, even though we're making a mobile app, we should make our website mobile-friendly. I personally hate having to download an app in order to interact with a website on my phone. Can test using [Jest](https://jestjs.io/) and [Jest image snapshot](https://github.com/americanexpress/jest-image-snapshot)

## Front-end style helpers
- Bootstrap
- Material design
- SASS

## Back-end options
- Node.js + Express.js
- Flask or Django (I would prefer using Python, since I think it would be cool to do ML/CV stuff, which has better support in Python. If we do use Python, we should use [static type checking](https://docs.python.org/3/library/typing.html))
- [Rocket](https://rocket.rs/) (Rust equivalent to Flask/Django)

I think a good option would be to stick to the MEAN/MERN stack and if we have an idea that can leverage ML/CV stuff, we can make a second Python API that is only exposed to the Node backend.

## Mobile options
- Native iOS: Swift/objc
- Native Android: Java/Kotlin
- Cross-platform
  - Flutter (Dart)
  - React Native (JS) - "React Native is not fully cross-platform, requiring that some components be developed using native language (such as camera functions), with some issues with lag on features. Nonetheless, the fact that 80% of the codebase can be shared across platforms makes React Native an attractive option compared to other cross-platform app frameworks." - [source](https://www.netsolutions.com/insights/tech-stack-for-web-mobile-app/)
  - Xamarin (C#)

Since (I think) I'm the only one on the team (so far) that has a Mac, we should probably not do native iOS. I prefer cross-platform, but am open to doing an Android native app if everyone else wants to do that.

## Misc
The professor suggests (not sure if it's a requirement) that we use Nginx for our web server and MongoDB for the database. We can prob just use those :)

We should unit test code for each of mobile, frontend, and backend using the respective tools for whatever stack we go with. It would be really cool if use [GitHub actions](https://docs.github.com/en/actions/learn-github-actions) to set up automatic [build/test](https://docs.github.com/en/actions/automating-builds-and-tests). We should also set up [linting](https://github.com/marketplace/actions/lint-action) as a GitHub action for whatever languages we go with.

We can optionally use [Redis](https://redis.io/docs/manual/client-side-caching/) for caching if we are limited by DB performance, but this might not help us if we have the DB on the same server as the application. Just mentioning since it could be an opportunity to learn an extra tool/get brownie points.

**Once we decide on stacks, I'll make new issues splitting out required setup tasks (e.g. setting up GitHub actions, etc.).**

**Comment by mplekunov** [comment]
Here is a problem though, from my understanding we MUST use EN part of MERN stack... so like, it doesn't look like we have much of the choice on backend?

**Comment by nashirj** [comment]
I think it's just recommended. The prof said we can use Python for the backend of the second project

**Comment by mplekunov** [comment]
> I think it's just recommended. The prof said we can use Python for the backend of the second project

Personally, I would rather go with Rust lol... I hate python for the luck of types, for the same reason I hate javascript

**Comment by mplekunov** [comment]
but EN could be better because Uber/Google/Ebay and other big companies use that

**Comment by mplekunov** [comment]
For Mobile options, I'm for cross-platform. From what I read, if you don't develop games or something that could actually utilize the "nativeness" part of the platfrom you develop for, cross-platform is the way. It will help us to actually being able to deploy our app on ANY mobile platform be it Android/iOS which would increase the number of potential users (hypothetically)

**Comment by mplekunov** [comment]
Also, no one in their right mind would use Java for Android. All new apps are written in Kotlin, Java is only used for maintaining old apps and that's basically it. Kotlin is like a better Java, plus google is developing JetPack Compose for Kotlin specifically which only proves the point that they are trying to get away from Java 🤣

**Comment by mplekunov** [comment]
Never used Flutter, heard that Dart is not a bad language though. C# is VERY nice language.... TRULLY OOP language. You can do a lot of OOP things in C# without being too verbose. Heard that React is technically a go to when it comes to cross platform though.

**Comment by mplekunov** [comment]
Also, I think Angular is nice for web app, and I actually like the fact that you can include Types in TypeScript but like... The person who will be responsible for web-app development will have to be good at time management and google because they will have to google a lot.

**Comment by nashirj** [comment]
Tentative decisions on some stacks:
Frontend: Vue.js (we can use [Material](https://mdbootstrap.com/docs/vue/#demo) for styling stuff)
Mobile: Flutter
Backend: Rocket, Flask only if we end up doing ML/CV stuff

**Comment by nashirj** [comment]
Here is a [sample app](https://github.com/GreenLoofa/vue-rocket) that uses vue and rocket

**Comment by mplekunov** [comment]
> Tentative decisions on some stacks: Frontend: Vue.js (we can use [Material](https://mdbootstrap.com/docs/vue/#demo) for styling stuff) Mobile: Flutter Backend: Rocket, Flask only if we end up doing ML/CV stuff

it's not "can" when it comes to Material... it's "must". Unless you want to spend endless time on doing css and stuff...

**Comment by nashirj** [comment]
There are other options, such as [bootstrap](https://bootstrap-vue.org/), which is why I said can - we will definitely use some CSS framework

**Comment by mplekunov** [comment]
Wouldn't material be better though? We can use material for both web app and mobile app which will give us UI consistency.

**Comment by mplekunov** [comment]
I could be misunderstanding it with Material design btw

**Comment by mplekunov** [comment]
nvm they support Rust

**Comment by nashirj** [comment]
Yeah we are also not 100% going to use Clarifai, just a possible idea

**Comment by mplekunov** [comment]
I guess we can solidify that for the backend we will use Rocket (Rust). I mean, I spent like 2-3 days trying to understand the syntax and different parts of Rocket/Rust, so there is no way I'm switching to anything else 😄

**Comment by nashirj** [comment]
I'm marking this as resolved, seems like we have our tech stack locked down.

**Comment by nashirj** [comment]
Just so that it's on the record, the professor said we need to use Node + Express, so we'll be using those instead of Rust + Rocket
